default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV.fetch('RDS_DB_NAME', 'wings_db') %>
  username: <%= ENV.fetch('RDS_USERNAME', 'wings_user') %>
  password: <%= ENV.fetch('RDS_PASSWORD', 'wings-pw') %>
  host: <%= ENV.fetch('RDS_HOSTNAME', 'localhost') %>
  port: <%= ENV.fetch('RDS_PORT', 5432) %>
development:
  <<: *default
  database: development
test:
  <<: *default
  database: test
staging:
  <<: *default
  encoding: unicode
  pool: 50
production:
  <<: *default
  encoding: unicode
  pool: 50